# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLfyFDeDlHcqhrCZcZATiZr3eSIWaLgv
"""

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

import pandas as pd
df = pd.read_csv('SDW2023.csv')
user_ids = df['UserID'].tolist()
print(user)

import requests
import json

def get_user(id):
  response = requests.get(f'{sdw2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))

!pip install openai

import os
import openai
openai.organization = "org-cJIBFRCj9IKPNJLW0wcoALci"
openai.api_key = os.getenv("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")

openai.api_key = "{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}"

def mensagem(user):
  mens = f"{user['name']}, Seu Futuro Brilha: Invista Hoje e Prospere!"
  return mens

for user in users:
  news = mensagem(user)
  print(news)

def update_user(user):
  response = requests.put(f"{sdw2023_api_url}/users/{user['id']}", json=user)
  return True if response.status_code == 200 else False

for user in users:
  success = update_user(user)
  print(f"User {user['name']} updated? {success}!")